[versions]
agp = "8.13.0"
kotlin = "2.1.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
lifecycleViewModel = "2.9.4"
hilt = "2.57.2"
iso8583 = "3.0.0"
dataStrore = "1.1.7"
coroutine = "1.10.2"
ksp = "2.1.10-1.0.31"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#ViewModel
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }

#Hilt
hilt-android = {group = "com.google.dagger" , name = "hilt-android" , version.ref = "hilt"}
hilt-compiler = {group = "com.google.dagger" , name = "hilt-android-compiler" , version.ref = "hilt"}

#ISO8583
iso8583 = {group = "net.sf.j8583" , name = "j8583" , version.ref = "iso8583"}

#DataStore
datastore-prefrences = {group = "androidx.datastore" , name = "datastore-preferences" , version.ref = "dataStrore"}

#Coroutine
coroutine = {group = "org.jetbrains.kotlinx" , name = "kotlinx-coroutines-android" , version.ref = "coroutine"}

#Debug
androidx-compose-debug = {group = "androidx.compose.ui" , name = "ui-tooling"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp" ,version.ref = "ksp"}
hilt-android = { id ="com.google.dagger.hilt.android" , version.ref = "hilt"}

